//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vapksPR7.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class author
    {
        public author()
        {
            this.books = new HashSet<books>();
        }
    
        public int id_author { get; set; }
        public string lastName { get; set; }
        public string name { get; set; }
        public string middleName { get; set; }
    
        public virtual ICollection<books> books { get; set; }
    }
}
