//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vapksPR7.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class books
    {
        public books()
        {
            this.process = new HashSet<process>();
        }
    
        public int id_book { get; set; }
        public string name { get; set; }
        public int id_genre { get; set; }
        public int id_author { get; set; }
        public decimal year { get; set; }
    
        public virtual author author { get; set; }
        public virtual genres genres { get; set; }
        public virtual ICollection<process> process { get; set; }
    }
}
