//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vapksPR7.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class genres
    {
        public genres()
        {
            this.books = new HashSet<books>();
        }
    
        public int id_genre { get; set; }
        public string genre { get; set; }
    
        public virtual ICollection<books> books { get; set; }
    }
}
