//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vapksPR7.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class process
    {
        public int id_process { get; set; }
        public int id_book { get; set; }
        public int id_status { get; set; }
    
        public virtual books books { get; set; }
        public virtual status status { get; set; }
    }
}
