//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vapksPR7.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class status
    {
        public status()
        {
            this.process = new HashSet<process>();
        }
    
        public int id_status { get; set; }
        public string status1 { get; set; }
    
        public virtual ICollection<process> process { get; set; }
    }
}
